import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useContext } from "react";
import Users from "./Users";
import axios, { AxiosError } from "axios";
import UserObj from "../models/userObj";
import classes from "../pages/posts/NewPost.module.scss";
import { AuthContext } from "../components/shared/context/auth-context";

const Home: NextPage<{ data: UserObj[]; myerror: any }> = (props) => {
  const auth = useContext(AuthContext);

  useEffect(() => {
    let storedUserData;
    if (localStorage.getItem("userData")) {
      storedUserData = JSON.parse(localStorage.getItem("userData")!);
    }
    if (storedUserData && storedUserData.token) {
      auth.login(storedUserData.userId, storedUserData.token);
    }
  }, [auth]);

  return (
    <React.Fragment>
      <Head>
        <title>Instasham</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Users data={props.data} />

      {props.myerror && (
        <p className={classes.placeForm}>
          Error fetching users: {props.myerror}
        </p>
      )}
    </React.Fragment>
  );
};

export default Home;

export async function getStaticProps() {
  let data = null;
  let myerror = null;
  try {
    const response = await axios({
      url: "http://localhost:5000/api/users",
      method: "GET",
    });
    data = await response.data;
  } catch (err) {
    const error = err as AxiosError;
    myerror = error.response?.data.message || null;
  }

  return { props: { data, myerror }, revalidate: 30 };
}
